/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import Control.ATM.ControlMenuPrincipal;
import Control.ATM.ControlRetirarExtrato;
import Entity.ATM.Conta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amiltonjunior
 */
public final class FrameRetirarExtrato extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameMenuOperacoes parentFrame;
    private final DefaultTableModel modelT;
    private Conta conta;
    
    /**
     * Creates new form FrameRetirarExtrato
     */
    public FrameRetirarExtrato() {
        initComponents();
        
        modelT = (DefaultTableModel) jTableExtrato.getModel();
        modelT.setRowCount(0); // Limpa a tabela
    }
    
    public void iniciar() {
        modelT.setRowCount(0); // Limpa a tabela
        
        ControlRetirarExtrato.iniciar(this);
    }
    
    public void setLabelData(String s) {
        labelData.setText(s);
    }
    
    // Método que armazena o JFrame pai
    public void setParentFrame(FrameMenuOperacoes parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    public void setNomeCliente(String nome) {
        jLabelNomeCliente.setText(nome);
    }
    
    public void setNumeroConta(String numero) {
        jLabelNumeroConta.setText(numero);
    }
    
    public void setLimite(String limite) {
        if (limite.equals("0.0"))
            jLabelLimite.setText("N/A");
        else
            jLabelLimite.setText(limite);
    }
    
    public void setTipo(String tipo) {
        jLabelTipo.setText(tipo);
        
        try {
            if (tipo.equals("poupanca"))
                setLabelData("Aniversário da conta:");
            else
                setLabelData("Data de abertura:");
        } catch (NullPointerException e) {
            setLabelData("Data de abertura:");
        }
    }
    
    public void setAniversario(String aniversario) {
        jLabelAniversario.setText(aniversario);
    }
    
    public void addExtrato(ArrayList<String> extrato) {
        modelT.addRow(new Object[]{extrato.get(0), extrato.get(1), extrato.get(2), extrato.get(3), extrato.get(4)});
    }

    public Conta getConta() {
        return conta;
    }

    public void setConta(Conta conta) {
        this.conta = conta;
    }
    
    // Método que retorna o JFrame pai
    public FrameMenuOperacoes getParentFrame() {
        return this.parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal6 = new javax.swing.JPanel();
        lblLogotipo6 = new javax.swing.JLabel();
        btnCancelar6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExtrato = new javax.swing.JTable();
        btnEfetuarDeposito7 = new javax.swing.JButton();
        lblSeta1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNumeroConta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelLimite = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelAniversario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal6.setBackground(new java.awt.Color(255, 255, 255));

        lblLogotipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        btnCancelar6.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnCancelar6.setText("Retornar");
        btnCancelar6.setFocusPainted(false);
        btnCancelar6.setFocusable(false);
        btnCancelar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelar6Clicked(evt);
            }
        });
        btnCancelar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Extrato");

        jTableExtrato.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jTableExtrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DATA. MOV.", "NR.DOC.", "OPERACAO", "VALOR", "SALDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExtrato.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableExtrato);

        btnEfetuarDeposito7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEfetuarDeposito7.setText("IMPRIMIR");
        btnEfetuarDeposito7.setFocusPainted(false);
        btnEfetuarDeposito7.setFocusable(false);
        btnEfetuarDeposito7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirclick(evt);
            }
        });
        btnEfetuarDeposito7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetuarDeposito7ActionPerformed(evt);
            }
        });

        lblSeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/esquerda.jpg"))); // NOI18N

        jLabel2.setText("Cliente: ");

        jLabelNomeCliente.setText("[NOMECLIENTE]");

        jLabel3.setText("Número da conta:");

        jLabelNumeroConta.setText("[NUMEROCONTA]");

        jLabel4.setText("Limite:");

        jLabelLimite.setText("[LIMITE]");

        jLabel5.setText("Tipo:");

        labelData.setText("[labelData]");

        jLabelTipo.setText("[TIPO]");

        jLabelAniversario.setText("[ANIVERSARIO]");

        javax.swing.GroupLayout PainelPrincipal6Layout = new javax.swing.GroupLayout(PainelPrincipal6);
        PainelPrincipal6.setLayout(PainelPrincipal6Layout);
        PainelPrincipal6Layout.setHorizontalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar6, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lblLogotipo6))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNomeCliente))
                                    .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelPrincipal6Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelLimite))
                                        .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelNumeroConta))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelTipo)
                                        .addGap(110, 110, 110)
                                        .addComponent(btnEfetuarDeposito7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addComponent(labelData)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelAniversario)))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PainelPrincipal6Layout.setVerticalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLogotipo6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelNomeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelNumeroConta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelLimite))
                        .addGap(25, 25, 25)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSeta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEfetuarDeposito7)
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabelTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelData)
                                    .addComponent(jLabelAniversario))))
                        .addGap(126, 126, 126))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelPrincipal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal6, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar6Clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar6Clicked
        // Chama a ação em ControlMenuPrincipal
        //ControlMenuPrincipal.cancelar(this, getParentFrame());
    }//GEN-LAST:event_btnCancelar6Clicked

    private void btnImprimirclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirclick

    private void btnCancelar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar6ActionPerformed
        ControlMenuPrincipal.cancelar(this, getParentFrame());
    }//GEN-LAST:event_btnCancelar6ActionPerformed

    private void btnEfetuarDeposito7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetuarDeposito7ActionPerformed
        ControlRetirarExtrato.imprimir(jTableExtrato, conta);
    }//GEN-LAST:event_btnEfetuarDeposito7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRetirarExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRetirarExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRetirarExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRetirarExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRetirarExtrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal6;
    private javax.swing.JButton btnCancelar6;
    private javax.swing.JButton btnEfetuarDeposito7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAniversario;
    private javax.swing.JLabel jLabelLimite;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumeroConta;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExtrato;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel lblLogotipo6;
    private javax.swing.JLabel lblSeta1;
    // End of variables declaration//GEN-END:variables
}
