
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import Control.ATM.ControlLeituraCartao;
import DAO.ATM.ContaDAO;
import Entity.ATM.Conta;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public final class FrameLeituraCartao extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameLeituraCartao parentFrame;
    private FrameMenuOperacoes nextFrame;
    private FrameErroLeituraCartao errorFrame;

    private List<Conta> contas;

    /**
     * Creates new form FrameLeituraCartao
     */
    public FrameLeituraCartao() {
        initComponents();

        clearInstance();
    }
    
    public void clearInstance() {
        try { 
            ContaDAO.getInstance().getEntity().clear();
            
            this.contas = ContaDAO.getInstance().findAll();

            cmbClientes.removeAllItems();
            cmbClientes.addItem("Selecione uma conta");

            for (Conta c : this.contas) {
                cmbClientes.addItem("AG: " + c.getAgencia() + " CONTA Nº " + c.getNumeroConta() + " CLIENTE: " + c.getCliente().getNome());
            }
        } catch (Exception e) {}
    }
    
    public Conta getConta(int index) {
        return contas.get(index);
    }

    public void recarregarClientes() {

        clearInstance();
        contas = ContaDAO.getInstance().findAll();

        cmbClientes.removeAllItems();
        cmbClientes.addItem("Selecione uma conta");

        for (Conta c : this.contas) {
            cmbClientes.addItem("AG: " + c.getAgencia() + " CONTA Nº " + c.getNumeroConta() + " CLIENTE: " + c.getCliente().getNome());
        }
    }
    
    

    // Método que armazena o JFrame pai
    public void setParentFrame(FrameLeituraCartao parentFrame) {
        this.parentFrame = parentFrame;
    }

    // Método que retorna o JFrame pai
    public FrameLeituraCartao getParentFrame() {
        return this.parentFrame;
    }

    // Método que armazena o próximo JFrame
    public void setNextFrame(FrameMenuOperacoes nextFrame) {
        this.nextFrame = nextFrame;
    }

    // Método que retorna o próximo JFrame
    public FrameMenuOperacoes getNextFrame() {
        return this.nextFrame;
    }

    // Método que armazena o JFrame de erro
    public void setErrorFrame(FrameErroLeituraCartao errorFrame) {
        this.errorFrame = errorFrame;
    }

    // Método que retorna o JFrame de erro
    public FrameErroLeituraCartao getErrorFrame() {
        return this.errorFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        lblLogotipo = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        btnInserirCartao = new javax.swing.JButton();
        btnErroLeitura = new javax.swing.JButton();
        cmbClientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setPreferredSize(new java.awt.Dimension(780, 530));

        lblLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        lblBemVindo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblBemVindo.setText("Seja bem-vindo(a)!");

        btnInserirCartao.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnInserirCartao.setText("Inserir o cartão na leitora");
        btnInserirCartao.setBorderPainted(false);
        btnInserirCartao.setFocusPainted(false);
        btnInserirCartao.setFocusable(false);
        btnInserirCartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserirCartaoCliked(evt);
            }
        });
        btnInserirCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCartaoActionPerformed(evt);
            }
        });

        btnErroLeitura.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnErroLeitura.setText("Simular erro de leitura");
        btnErroLeitura.setFocusPainted(false);
        btnErroLeitura.setFocusable(false);
        btnErroLeitura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnErroLeituraClicked(evt);
            }
        });

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblBemVindo)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnErroLeitura)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblLogotipo)
                        .addGap(245, 245, 245))))
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnInserirCartao)))
                .addGap(0, 154, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblLogotipo)
                .addGap(106, 106, 106)
                .addComponent(lblBemVindo)
                .addGap(54, 54, 54)
                .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInserirCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnErroLeitura)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirCartaoCliked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirCartaoCliked

        int index = cmbClientes.getSelectedIndex();

        if (index > 0) {
            // Chama a ação na classe ControlLeituraCartao
            ControlLeituraCartao.simularLeitura(this, getNextFrame(), contas.get(index-1));

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Selecione um cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
            cmbClientes.requestFocus();
        }
    }//GEN-LAST:event_btnInserirCartaoCliked

    private void btnErroLeituraClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnErroLeituraClicked
        // Chama a ação na classe ControlLeituraCartao
        ControlLeituraCartao.simularErroLeitura(this, getErrorFrame());
    }//GEN-LAST:event_btnErroLeituraClicked

    private void btnInserirCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirCartaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLeituraCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnErroLeitura;
    private javax.swing.JButton btnInserirCartao;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblLogotipo;
    // End of variables declaration//GEN-END:variables
}
