/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import Control.ATM.ControlMenuPrincipal;
import Entity.ATM.Conta;

/**
 *
 * @author amiltonjunior
 */
public class FrameMenuOperacoes extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameLeituraCartao parentFrame;
    private FrameConsultaSaldo frameConsultaSaldo;
    private FrameEfetuarDeposito frameEfetuarDeposito;
    private FrameEfetuarSaque frameEfetuarSaque;
    private FrameRetirarExtrato frameRetirarExtrato;
    private FramePaginaConstruindo framePaginaConstruindo;
    private Conta conta;
    
    /**
     * Creates new form FrameMenuEfetuarDeposito
     */
    public FrameMenuOperacoes() {
        initComponents();
    }
    
    // Método que armazena o JFrame pai
    public void setParentFrame(FrameLeituraCartao parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }
    
    // Método que retorna o JFrame pai
    public FrameLeituraCartao getParentFrame() {
        return this.parentFrame;
    }
    
    public Conta getConta() {
        return this.conta;
    }
    
    /* Métodos Sets */
    
    public void setFrameConsultaSaldo(FrameConsultaSaldo frame) {
        this.frameConsultaSaldo = frame;
    }
    
    public void setFrameEfetuarDeposito(FrameEfetuarDeposito frame) {
        this.frameEfetuarDeposito = frame;
    }
    
    public void setFrameEfetuarSaque(FrameEfetuarSaque frame) {
        this.frameEfetuarSaque = frame;
    }
    
    public void setFrameRetirarExtrato(FrameRetirarExtrato frame) {
        this.frameRetirarExtrato = frame;
    }
    
    public void setFramePaginaConstruindo(FramePaginaConstruindo frame) {
        this.framePaginaConstruindo = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal6 = new javax.swing.JPanel();
        lblLogotipo6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBMenudep = new javax.swing.JButton();
        jBMenusque = new javax.swing.JButton();
        jBMenuextrato = new javax.swing.JButton();
        jBMenutransfer = new javax.swing.JButton();
        jBMenuemp = new javax.swing.JButton();
        jBMenuoutros = new javax.swing.JButton();
        btnCancelar7 = new javax.swing.JButton();
        lblSeta28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal6.setBackground(new java.awt.Color(255, 255, 255));

        lblLogotipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        jBMenudep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenudep.setText("Depósito");
        jBMenudep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepositosclick(evt);
            }
        });
        jBMenudep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenudepActionPerformed(evt);
            }
        });

        jBMenusque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenusque.setText("Saque");
        jBMenusque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaqueclick(evt);
            }
        });
        jBMenusque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenusqueActionPerformed(evt);
            }
        });

        jBMenuextrato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenuextrato.setText("Extrato");
        jBMenuextrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExtratoSaldoclick(evt);
            }
        });
        jBMenuextrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuextratoActionPerformed(evt);
            }
        });

        jBMenutransfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenutransfer.setText("Transferência");
        jBMenutransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransfclick(evt);
            }
        });
        jBMenutransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenutransferActionPerformed(evt);
            }
        });

        jBMenuemp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenuemp.setText("Saldo");
        jBMenuemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaldoclick(evt);
            }
        });
        jBMenuemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuempActionPerformed(evt);
            }
        });

        jBMenuoutros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBMenuoutros.setText("Outros");
        jBMenuoutros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOutrosclick(evt);
            }
        });
        jBMenuoutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuoutrosActionPerformed(evt);
            }
        });

        btnCancelar7.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnCancelar7.setText("Sair");
        btnCancelar7.setFocusPainted(false);
        btnCancelar7.setFocusable(false);
        btnCancelar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelar7Clicked(evt);
            }
        });
        btnCancelar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar7ActionPerformed(evt);
            }
        });

        lblSeta28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/direita.jpg"))); // NOI18N

        javax.swing.GroupLayout PainelPrincipal6Layout = new javax.swing.GroupLayout(PainelPrincipal6);
        PainelPrincipal6.setLayout(PainelPrincipal6Layout);
        PainelPrincipal6Layout.setHorizontalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogotipo6)
                .addGap(236, 236, 236))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBMenusque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBMenuextrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBMenudep, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addGap(128, 128, 128)))
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBMenutransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBMenuemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBMenuoutros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                        .addComponent(btnCancelar7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeta28)
                        .addContainerGap())))
        );
        PainelPrincipal6Layout.setVerticalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblLogotipo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                        .addComponent(jBMenutransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jBMenuemp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBMenuoutros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addComponent(jBMenudep, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBMenusque, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jBMenuextrato, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSeta28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar7Clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar7Clicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar7Clicked

    private void btnDepositosclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositosclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepositosclick

    private void btnsaqueclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaqueclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaqueclick

    private void btnExtratoSaldoclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtratoSaldoclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExtratoSaldoclick

    private void btnTransfclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransfclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransfclick

    private void btnSaldoclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaldoclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoclick

    private void btnOutrosclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOutrosclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutrosclick

    private void btnCancelar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar7ActionPerformed
        ControlMenuPrincipal.cancelar(this, getParentFrame());
    }//GEN-LAST:event_btnCancelar7ActionPerformed

    private void jBMenudepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenudepActionPerformed
        ControlMenuPrincipal.efetuarDeposito(this, this.frameEfetuarDeposito);
    }//GEN-LAST:event_jBMenudepActionPerformed

    private void jBMenusqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenusqueActionPerformed
        ControlMenuPrincipal.efetuarSaque(this, this.frameEfetuarSaque);
    }//GEN-LAST:event_jBMenusqueActionPerformed

    private void jBMenuextratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuextratoActionPerformed
        ControlMenuPrincipal.retirarExtrato(this, this.frameRetirarExtrato);
    }//GEN-LAST:event_jBMenuextratoActionPerformed

    private void jBMenutransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenutransferActionPerformed
        ControlMenuPrincipal.Transferir(this, this.framePaginaConstruindo);
    }//GEN-LAST:event_jBMenutransferActionPerformed

    private void jBMenuempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuempActionPerformed
        ControlMenuPrincipal.verSaldo(this, this.frameConsultaSaldo);
    }//GEN-LAST:event_jBMenuempActionPerformed

    private void jBMenuoutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuoutrosActionPerformed
        ControlMenuPrincipal.menuOutros(this, this.framePaginaConstruindo);
    }//GEN-LAST:event_jBMenuoutrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenuOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenuOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenuOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenuOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenuOperacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal6;
    private javax.swing.JButton btnCancelar7;
    private javax.swing.JButton jBMenudep;
    private javax.swing.JButton jBMenuemp;
    private javax.swing.JButton jBMenuextrato;
    private javax.swing.JButton jBMenuoutros;
    private javax.swing.JButton jBMenusque;
    private javax.swing.JButton jBMenutransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogotipo6;
    private javax.swing.JLabel lblSeta28;
    // End of variables declaration//GEN-END:variables
}
