/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import Control.ATM.ControlMenuPrincipal;

/**
 *
 * @author amiltonjunior
 */
public class FrameErroLeituraCartao extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameLeituraCartao parentFrame;
    
    /**
     * Creates new form FrameErroLeituraCartao
     */
    public FrameErroLeituraCartao() {
        initComponents();
    }
    
    public void setContaBloqueada() {
        lblTenteNovamente.setText("Sua conta está bloqueada!");
    }
    
    public void resetContaBloqueada() {
        lblTenteNovamente.setText("Por favor, tente novamente.");
    }
    
    // Método que armazena o JFrame pai
    public void setParentFrame(FrameLeituraCartao parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    // Método que retorna o JFrame pai
    public FrameLeituraCartao getParentFrame() {
        return this.parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        lblLogotipo = new javax.swing.JLabel();
        lblErroLeitura = new javax.swing.JLabel();
        lblIconeErroLeitura = new javax.swing.JLabel();
        lblTenteNovamente = new javax.swing.JLabel();
        lblSeta1 = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        lblErroLeitura.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblErroLeitura.setText("Erro ao fazer a leitura do cartão!");

        lblIconeErroLeitura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/erro.jpg"))); // NOI18N

        lblTenteNovamente.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblTenteNovamente.setText("Por favor, tente novamente.");

        lblSeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/esquerda.jpg"))); // NOI18N

        btnRetornar.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btnRetornar.setText("Retornar");
        btnRetornar.setFocusPainted(false);
        btnRetornar.setFocusable(false);
        btnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetornarClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblIconeErroLeitura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErroLeitura)
                            .addComponent(lblLogotipo)
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblTenteNovamente))))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconeErroLeitura)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblLogotipo)
                        .addGap(156, 156, 156)
                        .addComponent(lblErroLeitura)))
                .addGap(42, 42, 42)
                .addComponent(lblTenteNovamente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeta1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRetornar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornarClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarClicked
        // Chama a ação na classe ControlMenuPrincipal
        ControlMenuPrincipal.cancelar(this, getParentFrame());
        resetContaBloqueada();
    }//GEN-LAST:event_btnRetornarClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameErroLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameErroLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameErroLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameErroLeituraCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameErroLeituraCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel lblErroLeitura;
    private javax.swing.JLabel lblIconeErroLeitura;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblSeta1;
    private javax.swing.JLabel lblTenteNovamente;
    // End of variables declaration//GEN-END:variables
}
