/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

/**
 *
 * @author amiltonjunior
 */
public class PaginaATM extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
//    private static Map<Integer, Map<String, ArrayList<String>>> bdClientes;

    /**
     * Creates new form PaginaInicialATM
     *
     * @param parent
     * @param modal
     */
    public PaginaATM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco MM - MoneyMaker");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(780, 495));
        setMinimumSize(new java.awt.Dimension(780, 495));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaginaATM dialog = new PaginaATM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                // JFrames
                FrameLeituraCartao frameLeituraCartao = new FrameLeituraCartao();
                FrameMenuOperacoes frameMenuOperacoes = new FrameMenuOperacoes();
                FrameErroLeituraCartao frameErroLeituraCartao = new FrameErroLeituraCartao();
                FrameConsultaSaldo frameConsultaSaldo = new FrameConsultaSaldo();
                FrameEfetuarDeposito frameEfetuarDeposito = new FrameEfetuarDeposito();
                FrameEfetuarSaque frameEfetuarSaque = new FrameEfetuarSaque();
                FrameRetirarExtrato frameRetirarExtrato = new FrameRetirarExtrato();
                FramePaginaConstruindo framePaginaConstruindo = new FramePaginaConstruindo();
                FrameSucessoTransacao frameSucessoTransacao = new FrameSucessoTransacao();
                FrameErroTransacao frameErroTransacao = new FrameErroTransacao();

                // Define o JFrame pai
                frameMenuOperacoes.setParentFrame(frameLeituraCartao);
                frameErroLeituraCartao.setParentFrame(frameLeituraCartao);
                frameConsultaSaldo.setParentFrame(frameMenuOperacoes);
                frameEfetuarDeposito.setParentFrame(frameMenuOperacoes);
                frameEfetuarSaque.setParentFrame(frameMenuOperacoes);
                frameRetirarExtrato.setParentFrame(frameMenuOperacoes);
                framePaginaConstruindo.setParentFrame(frameMenuOperacoes);
                frameErroTransacao.setParentFrame(frameMenuOperacoes);
                frameSucessoTransacao.setParentFrame(frameMenuOperacoes);

                // Define os próximos JFrames
                frameLeituraCartao.setNextFrame(frameMenuOperacoes);
                frameLeituraCartao.setErrorFrame(frameErroLeituraCartao);

                // Define os frames de erro e sucesso
                frameEfetuarDeposito.setFrameSucesso(frameSucessoTransacao);
                frameEfetuarDeposito.setFrameErro(frameErroTransacao);
                frameEfetuarSaque.setFrameSucesso(frameSucessoTransacao);
                frameEfetuarSaque.setFrameErro(frameErroTransacao);

                // Define os JFrames do menu principal
                frameMenuOperacoes.setFrameConsultaSaldo(frameConsultaSaldo);
                frameMenuOperacoes.setFrameEfetuarDeposito(frameEfetuarDeposito);
                frameMenuOperacoes.setFrameEfetuarSaque(frameEfetuarSaque);
                frameMenuOperacoes.setFrameRetirarExtrato(frameRetirarExtrato);
                frameMenuOperacoes.setFramePaginaConstruindo(framePaginaConstruindo);

                // Alinha no centro
                frameLeituraCartao.setLocationRelativeTo(null);
                frameMenuOperacoes.setLocationRelativeTo(null);
                frameErroLeituraCartao.setLocationRelativeTo(null);
                frameConsultaSaldo.setLocationRelativeTo(null);
                frameEfetuarDeposito.setLocationRelativeTo(null);
                frameEfetuarSaque.setLocationRelativeTo(null);
                frameRetirarExtrato.setLocationRelativeTo(null);
                framePaginaConstruindo.setLocationRelativeTo(null);
                frameErroTransacao.setLocationRelativeTo(null);
                frameSucessoTransacao.setLocationRelativeTo(null);

                // Exibe o JFrame principal
                frameLeituraCartao.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
